db.url=jdbc:postgresql://localhost:5433/dmdev_http_course
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver

image.base.url=/Users/Maksym/IdeaProjects/DmDev/http-servlets-starter/http-servlets-starter/resources/download